apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xtp3
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-xtp3@sha256:66d85f87ed21915136d5ea5e643f0a85d74dd0c48fc38b76bd2fa868c7d6538e
        name: my-nodejs
        resources: {}
status: {}
